package com.unitfunction.common.database.daogenerate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.unitfunction.common.database.DataEntity;

import com.unitfunction.common.database.daogenerate.DataEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataEntityDaoConfig;

    private final DataEntityDao dataEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataEntityDaoConfig = daoConfigMap.get(DataEntityDao.class).clone();
        dataEntityDaoConfig.initIdentityScope(type);

        dataEntityDao = new DataEntityDao(dataEntityDaoConfig, this);

        registerDao(DataEntity.class, dataEntityDao);
    }
    
    public void clear() {
        dataEntityDaoConfig.clearIdentityScope();
    }

    public DataEntityDao getDataEntityDao() {
        return dataEntityDao;
    }

}
